# Generated by Django 3.2.9 on 2021-12-18 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211217_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 18, 9, 37, 53, 419196, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
