# Generated by Django 3.2.9 on 2021-12-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_review_createdat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.RemoveField(
            model_name='review',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, help_text='Product Image URL', max_length=1000, null=True),
        ),
    ]
