# Generated by Django 3.2.9 on 2021-12-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, help_text='Product Name', max_length=800, null=True)),
                ('category', models.CharField(blank=True, help_text='Product Category', max_length=150, null=True)),
                ('sub_category', models.CharField(blank=True, help_text='Product Sub Category', max_length=150, null=True)),
                ('brand', models.CharField(blank=True, help_text='Product Brand', max_length=400, null=True)),
                ('sale_price', models.CharField(blank=True, help_text='Product sales price', max_length=400, null=True)),
                ('market_price', models.CharField(blank=True, help_text='Product Market price', max_length=400, null=True)),
                ('image_url', models.CharField(blank=True, help_text='Product Image URL', max_length=1000, null=True)),
                ('p_url', models.CharField(blank=True, help_text='Product URL', max_length=1000, null=True)),
                ('type', models.CharField(blank=True, help_text='Product Type', max_length=3000, null=True)),
                ('eancode', models.CharField(blank=True, help_text='Product EAN Code', max_length=3000, null=True)),
                ('rating', models.CharField(blank=True, help_text='Product Rating', max_length=3000, null=True)),
                ('description', models.CharField(blank=True, help_text='Product Description', max_length=50000, null=True)),
            ],
        ),
    ]
